In [4]:
from selenium import webdriver
browser = webdriver.Chrome('C:/Users/Administrator/Desktop/chromedriver/chromedriver.exe')

In [5]:
naukri_url = "https://www.naukri.com/data-science-jobs"
browser.get(naukri_url)

In [14]:
jobs = browser.find_elements_by_css_selector('div.row[type="tuple"]')
len(jobs)

50

In [28]:
import pandas as pd

def get_info(job, selector, attribute):
    try:
        tag = job.find_element_by_css_selector(selector)
        tag = tag.get_attribute(attribute)
    except:
        tag = None
    return tag


df_jobs = pd.DataFrame(columns = ['Title','Company','Salary','Date','Location','Experience','Skills','Description','URL'])



for job in jobs:
    job_title = get_info(job, 'li.desig', 'title')
    company = get_info(job,'span.org','innerHTML')
    salary = get_info(job, 'span.salary','innerHTML')
    date = get_info(job, 'span.date','innerHTML')
    
    
    
    try:
        parent_location = job.find_element_by_css_selector('span.loc')
        location = get_info(parent_location, 'span','innerHTML')
    except:
        location = None
    
    experience = get_info(job, 'span.exp', 'innerHTML')
    
    skills = get_info(job, 'span.skill', 'innerHTML') 
    
    description = get_info(job, 'span.desc', 'innerHTML')
    
    url = get_info(job, 'a.content', 'href')
    
    curr_job = {'Title' : job_title,'Company' : company,'Salary' : salary,'Date' : date,'Location' : location,
                'Experience' : experience,'Skills' : skills, 'Description' : description, 'URL' : url}

    df_jobs = df_jobs.append(curr_job, ignore_index = True)

In [89]:
import re
def cut(v):
    try:
        print(v.split("   ")[1])
    except:
        print(v.split("  ")[1])

In [90]:
df_jobs['Salary'].apply(cut)

 2,00,000 - 7,00,000 P.A.
 5,00,000 - 10,00,000 P.A.
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
 1,25,000 - 3,00,000 P.A.
 10,00,000 - 15,00,000 P.A.
Not disclosed
Not disclosed
Not disclosed
Not disclosed
 2,00,000 - 4,25,000 P.A.
Not disclosed
 Rs 101900-3000(4)-113900 (5 years).
 4,00,000 - 8,00,000 P.A.
 2,50,000 - 7,50,000 P.A.
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
 1,00,000 - 3,00,000 P.A.
 1,25,000 - 4,00,000 P.A. Best salary as per Industry &amp; ...
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
 4,00,000 - 7,50,000 P.A.
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed
Not disclosed

0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
20    None
21    None
22    None
23    None
24    None
25    None
26    None
27    None
28    None
29    None
30    None
31    None
32    None
33    None
34    None
35    None
36    None
37    None
38    None
39    None
40    None
41    None
42    None
43    None
44    None
45    None
46    None
47    None
48    None
49    None
Name: Salary, dtype: object

In [85]:
df_jobs

,Title,Company,Salary,Date,Location,Experience,Skills,Description,URL,salary
0,Data Science,Netcore Solutions Pvt Ltd,"<em></em> 2,00,000 - 7,00,000 P.A.",3 days ago,Mumbai,<em></em>2-4 yrs,"Algorithms, Machine Learning, Python, Java, <f...","At least 2 year of experience in <font class=""...",https://www.naukri.com/job-listings-Data-Scien...,None
1,Analyst / Sr. Analyst (data Science),Cvent India Pvt. Ltd.,"<em></em> 5,00,000 - 10,00,000 P.A.",2 days ago,Gurgaon,<em></em>5-8 yrs,"predictive modeling, predictive analytics, mac...",Strong experience on providing predictive mode...,https://www.naukri.com/job-listings-Analyst-Sr...,None
2,Group Manager - Data Science - Python/nlp,Staffio HR,<em></em> Not disclosed,3 days ago,Bengaluru,<em></em>6-11 yrs,"machine learning, text mining, r, nlp, <font c...",- This is a Team management role - Skill set ...,https://www.naukri.com/job-listings-Group-Mana...,None
3,Solution Architect - Data Science,Quantiphi Analytics Solutions Pvt. Ltd.,<em></em> Not disclosed,5 days ago,Mumbai,<em></em>4-9 yrs,"Deep Learning, Python, NLP, <font class=""hlite...",- The experience of working in a category defi...,https://www.naukri.com/job-listings-Solution-A...,None
4,Director - Data Science,Rinalytics Advisors,<em></em> Not disclosed,5 days ago,Anywhere inindia,<em></em>10-15 yrs,"<font class=""hlite"">Data</font> <font class=""h...",Masters or PhD with experience in the area of ...,https://www.naukri.com/job-listings-Director-D...,None
5,Data Science Engineer - Machine Learning,Resource Weaver,<em></em> Not disclosed,5 days ago,Chennai,<em></em>5-10 yrs,"Hadoop, Hive, <font class=""hlite"">Data</font> ...",- Experience with machine learning algorithms ...,https://www.naukri.com/job-listings-Data-Scien...,None
6,Data Science Research Manager - IT,Peopleton Solutions,<em></em> Not disclosed,6 days ago,Bengaluru,<em></em>10-15 yrs,"R, Analytics, SQL, Statistical Modeling, Machi...",- Working experience with machine learning alg...,https://www.naukri.com/job-listings-Data-Scien...,None
7,Opening For FULL / PART TIME Trainer in DATA S...,"<font class=""hlite"">Data</font> <font class=""h...","<em></em> 1,25,000 - 3,00,000 P.A.",7 days ago,Noida(Sector-2 Noida),<em></em>0-2 yrs,"ec, ee, cs, mca, bca, 2013, 2014, ai, machine ...",None,https://www.naukri.com/job-listings-Opening-Fo...,None
8,ETL Lead & Data Science,COMPUTER POWER GROUP PRIVATE LIMITED,"<em></em> 10,00,000 - 15,00,000 P.A.",3 days ago,"Chennai, Bengaluru, Mumbai, Pune, Noida",<em></em>7-10 yrs,"SQL, <font class=""hlite"">Data</font> Analysis,...",Industry experience in building and operationa...,https://www.naukri.com/job-listings-ETL-Lead-D...,None
9,Specialist - Data Science,Brainsearch Consulting Pvt Ltd.Â&nbsp;,<em></em> Not disclosed,3 days ago,"Delhi NCR, Bengaluru, Gurgaon",<em></em>7-12 yrs,"Specialist - <font class=""hlite"">Data</font> <...","- Experience with one or more <font class=""hli...",https://www.naukri.com/job-listings-Specialist...,None
10,Manager - Operations - Data Science Course - E...,Change Leaders,<em></em> Not disclosed,5 days ago,Bengaluru,<em></em>3-6 yrs,"Operations, Manager - Operations, Project Mana...","- Ownership of Program Office (<font class=""hl...",https://www.naukri.com/job-listings-Manager-Op...,None
11,Walk-in Drive for Data Science on 29th Sep @ B...,Hexaware Technologies Ltd.,<em></em> Not disclosed,6 days ago,Bengaluru,<em></em>4-9 yrs,"Text Mining, Hive, Hadoop, SQL, <font class=""h...",None,https://www.naukri.com/job-listings-Walk-in-Dr...,None
12,Immediate Requirement for Data Science Trainer...,Peers Technologies (P) Ltd.,<em></em> Not disclosed,7 days ago,Hyderabad,<em></em>3-8 yrs,"<font class=""hlite"">data</font> <font class=""h...",None,https://www.naukri.com/job-listings-Immediate-...,None
13,"Data Analyst / Data Science - Excel,sql,sas,py...",SLA Consultants India,"<em></em> 2,00,000 - 4,25,000 P.A.",4 days ago,"Delhi NCR, Gurgaon, Noida",<em></em>0-5 yrs,"<font class=""hlite"">data</font> analyst, repor...",None,https://www.naukri.com/job-listings-Data-Analy...,None
14,Data Science Engineer,HighPoints Technologies India (P) Ltd.,<em></em> Not disclosed,7 days ago,Hyderabad,<em></em>5-10 yrs,"<font class=""hlite"">Data</font> <font class=""h...","Experience of <font class=""hlite"">data</font> ...",https://www.naukri.com/job-listings-Data-Scien...,None
15,Director (Grade F) - Data Sciences Lab,Reserve Bank of India (RBI),<em></em> Rs 101900-3000(4)-113900 (5 years...,2 days ago,Mumbai,<em></em>15-20 yrs,None,None,https://www.naukri.com/job-listings-Director-G...,None
16,Trainee Data Science,MNC,"<em></em> 4,00,000 - 8,00,000 P.A.",4 days ago,"Mumbai, Bengaluru, Pune",<em></em>0-1 yrs,"<font class=""hlite"">data</font> <font class=""h...",None,https://www.naukri.com/job-listings-Trainee-Da...,None
17,Talent Search Consultant - Data Science & Anal...,Rinalytics Advisors Pvt. Ltd,"<em></em> 2,50,000 - 7,50,000 P.A.",7 days ago,"Bengaluru, Chennai",<em></em>2-7 yrs,"Hiring, <font class=""hlite"">Data</font> <font ...",None,https://www.naukri.com/job-listings-Talent-Sea...,None
18,Senior Consultant (data Sciences),AbsolutData Research Analytics Solutions Pvt. Lt,<em></em> Not disclosed,13 days ago,Gurgaon,<em></em>6-8 yrs,"Natural Language Processing, NLP, <font class=...",Experience in productionizing the machine lear...,https://www.naukri.com/job-listings-Senior-Con...,None
19,Data Science Manager,Allstate Solutions Private Limited,<em></em> Not disclosed,5 days ago,"Bengaluru, Pune",<em></em>6-10 yrs,"Business analysis, Analytical, <font class=""hl...","Excellent knowledge of open <font class=""hlite...",https://www.naukri.com/job-listings-Data-Scien...,None
20,Data Science,Walking Tree Consultancy Services,<em></em> Not disclosed,7 days ago,"Hyderabad, Pune",<em></em>3-8 yrs,"<font class=""hlite"">Data</font> <font class=""h...",2-5 years of progressive experience in buildin...,https://www.naukri.com/job-listings-Data-Scien...,None
21,Data Science Analytics Trainer - Part Time (we...,MARSIAN Technologies LLP,<em></em> Not disclosed,10 days ago,Pune(Viman Nagar),<em></em>4-9 yrs,"machine learning, <font class=""hlite"">data</fo...",Classes need to be conducted only in weekends ...,https://www.naukri.com/job-listings-Data-Scien...,None
22,Strategic Project & Operations - Data Science ...,BlackRock Services India Pvt. Ltd.,<em></em> Not disclosed,11 days ago,Gurgaon,<em></em>5-8 yrs,"<font class=""hlite"">Data</font> <font class=""h...",None,https://www.naukri.com/job-listings-Strategic-...,None
23,Data Science Engineer,Startup - Involvio,<em></em> Not disclosed,7 days ago,"Bengaluru, Noida",<em></em>3-7 yrs,"Hive, NoSQL, HBase, Pig, Cassandra, SQL, Machi...","Experience with common <font class=""hlite"">dat...",https://www.naukri.com/job-listings-Data-Scien...,None
24,Associate Project Manager- Data Science,IRIS SOFTWARE Inc,<em></em> Not disclosed,12 days ago,Noida,<em></em>8-12 yrs,"deep learning, natural language processing, in...",Should have managed 10-20 team member projects...,https://www.naukri.com/job-listings-Associate-...,None
25,Head - Data Science & Analytics - Financial Se...,Dimensions HRD Consultants,<em></em> Not disclosed,12 days ago,Noida,<em></em>6-11 yrs,"<font class=""hlite"">Data</font> <font class=""h...",- Incumbent must have Operational understandin...,https://www.naukri.com/job-listings-Head-Data-...,None
26,Data Science Engineer - Machine Learning/r,Vidooly - Startup,<em></em> Not disclosed,12 days ago,Hyderabad,<em></em>3-7 yrs,"Machine Learning, Deep Learning, Natural Langu...","BS/ MS in computer <font class=""hlite"">science...",https://www.naukri.com/job-listings-Data-Scien...,None
27,Data Science/data Scientist - Machine Learning,Matrimony.com Limited,<em></em> Not disclosed,12 days ago,Chennai(Mandaveli),<em></em>7-12 yrs,"Deep Learning, <font class=""hlite"">Data</font>...",Contribute to the improvement of <font class=...,https://www.naukri.com/job-listings-Data-Scien...,None
28,Urgent Hiring for Full Time Trainer in DATA Sc...,K V Computer Home Private limited,"<em></em> 1,00,000 - 3,00,000 P.A.",9 days ago,Noida,<em></em>0-3 yrs,"<font class=""hlite"">data</font> <font class=""h...",None,https://www.naukri.com/job-listings-Urgent-Hir...,None
29,Data Science Trainer / Bigdata Hadoop Trainer ...,Piford Technologies (P) Ltd,"<em></em> 1,25,000 - 4,00,000 P.A. Best sal...",9 days ago,"Chandigarh, Mohali",<em></em>0-5 yrs,"machine learning, <font class=""hlite"">data</fo...",None,https://www.naukri.com/job-listings-Data-Scien...,None
30,Data Science Engineer @ Pune,iglance Systems LLP,<em></em> Not disclosed,14 days ago,Pune,<em></em>8-13 yrs,"Machine Learning, <font class=""hlite"">Data</fo...",None,https://www.naukri.com/job-listings-Data-Scien...,None
31,SPi Technology - DATA Science Company - Lookin...,SPI TECHNOLOGIES INDIA PRIVATE LIMITED,<em></em> Not disclosed,20 days ago,Chennai,<em></em>3-8 yrs,"<font class=""hlite"">data</font> <font class=""h...",Demonstrated capability to pick up required so...,https://www.naukri.com/job-listings-SPi-Techno...,None
32,Cyber Security Data Science Engineer,JoulestoWatts Business Solutions Pvt Ltd,<em></em> Not disclosed,17 days ago,Bengaluru,<em></em>2-7 yrs,"Spark, Java, SCALA, Hadoop, <font class=""hlite...",1) Must have experience of working with cyber ...,https://www.naukri.com/job-listings-Cyber-Secu...,None
33,Data Science Trainer,Pathfinder Enterprise Solutions Pvt Ltd,<em></em> Not disclosed,19 days ago,Chennai,<em></em>10-15 yrs,"Deep Learning, NLP, Linear Regression, <font c...","About 10+ years experience in <font class=""hli...",https://www.naukri.com/job-listings-Data-Scien...,None
34,"Big Data, Data Science and AI Engineer",Startup - icliniq.com,<em></em> Not disclosed,19 days ago,Coimbatore,<em></em>2-5 yrs,"<font class=""hlite"">Data</font> <font class=""h...",Proven experience in working with Big <font cl...,https://www.naukri.com/job-listings-Big-Data-D...,None
35,"Data Science - 3+ Years of exp , Chennai",Tekclan Software Solutions Private limited,<em></em> Not disclosed,19 days ago,Chennai(Dhandeeswaram Nagar),<em></em>2-7 yrs,"Deep Learning, Machine Learning, NLP, Python, ...",3 + years experience with analytical software ...,https://www.naukri.com/job-listings-Data-Scien...,None
36,Data Science/ Python Developer,Polestar Solutions And Services India Pvt. Ltd.,"<em></em> 4,00,000 - 7,50,000 P.A.",23 days ago,Noida(Sector-59 Noida),<em></em>2-7 yrs,"Python, Django, <font class=""hlite"">Data</font...",Should have 2+ years creating predictive model...,https://www.naukri.com/job-listings-Data-Scien...,None
37,Data Science (jupyter/azure Ml/matlab),Accenture,<em></em> Not disclosed,24 days ago,Bengaluru,<em></em>1-5 yrs,"MATLAB, <font class=""hlite"">Data</font> mining...",None,https://www.naukri.com/job-listings-Data-Scien...,None
38,Data Science (jupyter/azure Ml/matlab),Accenture,<em></em> Not disclosed,24 days ago,Bengaluru,<em></em>1-5 yrs,"Python, MATLAB, <font class=""hlite"">Data</font...",None,https://www.naukri.com/job-listings-Data-Scien...,None
39,Data Science (jupyter/azure Ml/matlab),Accenture,<em></em> Not disclosed,25 days ago,Bengaluru,<em></em>2-5 yrs,"Python, MATLAB, <font class=""hlite"">Data</font...",None,https://www.naukri.com/job-listings-Data-Scien...,None
40,"Data Science,machine Learning, NLP, SAS, R, Mo...",Careernet Technologies Pvt Ltd,<em></em> Not disclosed,29 days ago,Mumbai,<em></em>7-11 yrs,"hadoop, nosql, <font class=""hlite"">data</font>...",At least 7 years of work experience as a <font...,https://www.naukri.com/job-listings-Data-Scien...,None
41,Data Science (jupyter/azure Ml/matlab),Accenture,<em></em> Not disclosed,27 days ago,Bengaluru,<em></em>4-7 yrs,"SAP, Python, MATLAB, Enterprise applications, ...",Accenture Technology powers our clients busine...,https://www.naukri.com/job-listings-Data-Scien...,None
42,"Data Science Associate Consultant (pune, India)",ZS Associates {India} Pvt Ltd,<em></em> Not disclosed,28 days ago,Pune,<em></em>3-5 yrs,"<font class=""hlite"">data</font> <font class=""h...",None,https://www.naukri.com/job-listings-Data-Scien...,None
43,Data Science Associate Consultant,ZS Associates {India} Pvt Ltd,<em></em> Not disclosed,26 days ago,Delhi,<em></em>3-5 yrs,"Text Mining, <font class=""hlite"">Data</font> <...","High motivation, good work ethic and maturity;...",https://www.naukri.com/job-listings-Data-Scien...,None
44,Data Science Lead,D Cube Analytics- Startup,<em></em> Not disclosed,26 days ago,Bengaluru,<em></em>5-10 yrs,"<font class=""hlite"">Data</font> <font class=""h...",Experience in applying machine learning techni...,https://www.naukri.com/job-listings-Data-Scien...,None
45,Data Science Manager,Nice interactive solutions India pvt ltd,<em></em> Not disclosed,28 days ago,Pune,<em></em>12-22 yrs,"<font class=""hlite"">data</font> <font class=""h...",Liaise with the scrum master and scrum teams t...,https://www.naukri.com/job-listings-Data-Scien...,None
46,Head - Data Science/enterprise AI - PhD,Rinalytics Advisors,<em></em> Not disclosed,31 days ago,"Bengaluru, Hyderabad, Pune",<em></em>12-18 yrs,"solutioning, <font class=""hlite"">data</font> <...","- Pre-sales, solutioning, delivery experience;...",https://www.naukri.com/job-listings-Head-Data-...,None
47,Data Science Engineer - Machine Learning,Kalagato - Startup,<em></em> Not disclosed,31 days ago,Delhi NCR,<em></em>1-5 yrs,"Machine Learning, Python, NLP, Neural Networks...","1-5 years of work experience, prior experience...",https://www.naukri.com/job-listings-Data-Scien...,None
48,Data Science for Banking,Accenture,<em></em> Not disclosed,32 days ago,Bengaluru,<em></em>4-8 yrs,"Python, Machine learning, Outsourcing, Artific...",Accenture Technology powers our clients busine...,https://www.naukri.com/job-listings-Data-Scien...,None
49,Director of Data Science,Deal4Loans - Startup,<em></em> Not disclosed,39 days ago,Noida,<em></em>5-8 yrs,"<font class=""hlite"">Data</font> <font class=""h...",You should be able to develop high-level relat...,https://www.naukri.com/job-listings-Director-o...,None